[module]
[[module.imports]]
  path = 'github.com/LordMathis/hugo-theme-nightfall'

baseURL = 'https://rmonaghan.com/'
languageCode = 'en-us'
title = 'Ryan Monaghan'
theme = "hugo-theme-nightfall"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
author = "Ryan Monaghan"
user = "ryan"
hostname = "rmoanghan.com"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/coffee2theorems"

[[params.social]]
key = 1
name = "mastodon"
url = "https://mastodon.social/@rmonaghan"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/ryan-k-monaghan/"