[module]
[[module.imports]]
  path = 'github.com/LordMathis/hugo-theme-nightfall'

baseURL = 'https://rmonaghan.com/'
languageCode = 'en-us'
title = 'Ryan Monaghan'
theme = "hugo-theme-nightfall"

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "/blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "/about"

[params]
author = "Ryan Monaghan"
user = "ryan"
hostname = "rmonaghan"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/coffee2theorems"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/ryan-k-monaghan/"