baseURL = 'https://rmonaghan.com/'
languageCode = 'en-us'
title = 'Ryan Monaghan'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

SectionPagesMenu = "main"
Paginate = 3 
enableRobotsTXT = true

custom_css = ["static/css/custom.css"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Ryan Monaghan"
  favicon = "favicon.ico"
  site_logo = "favicon.ico"
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

